schema: http://localhost:8000/graphql
# schema: https://4pay.ai/backend/graphql
documents: ./src/framework/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
