import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/thumbs';
import 'swiper/css/scrollbar';
import 'swiper/css/a11y';
import 'swiper/css/autoplay';
import 'swiper/css/controller';
import "swiper/css/mousewheel";
import 'swiper/css/grid';
export { Navigation, Thumbs, Pagination, FreeMode } from 'swiper/modules';
export { Swiper, SwiperSlide } from 'swiper/react';
export type { SwiperOptions } from 'swiper/types';
