# schema: ${NEXT_PUBLIC_GRAPHQL_API_ENDPOINT}
schema: https://knockknock.mx/backend/graphql
documents: ./src/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
