schema: http://localhost:8000/graphql
#schema: https://knockknock.mx/backend/graphql
documents: ./src/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
